 var ob = [
  {
    id : "2911",
    events : ["1929 - On 31 December 1929, Congress passed the historic resolution declaring Purna Swaraj as its goal.",
        "1922-Birth of Swaraj Party - Chittaranjan Das - President - Motilal Nehru - Secretary",
    "1600-East India Company was given the Royal charter"]  
  },
  {
    id : "3111",
    events : ["1929 - On 31 December 1929, Congress passed the historic resolution declaring Purna Swaraj as its goal.",
        "1922-Birth of Swaraj Party - Chittaranjan Das - President - Motilal Nehru - Secretary",
    "1600-East India Company was given the Royal charter"]  
  },
  {
    id : "3011", 
    events : ["In the year 1877, Queen Victoria of the erstwhile British Empire is proclaimed the Empress of India.",
    "During the 1949 war with Pakistan – Prime Minister approached United Nations against the armed insurgency by Pakistan. According to an UN decree, a cease-fire took effect on this date and the war between the two countries stopped and a status-quo was maintained thereafter."]
  },{
    id : "20", 
    events : ["A 1975 bomb blast at Samastipur, Bihar fatally wounded the then Minister of Railways, Lalit Narayan Mishra. The sessions court gave a verdict in a trial after 39 years which convicted 5 accused of secretly plotting and murdering the minister and 3 others. The verdict was later quashed by the high court and all of accused were acquitted.",
    "Mannathu Padnabha Pillai – The social reformer and freedom fighter from the state of Kerala was born in 1878 in the erstwhile princely state of Travancore. He dedicated his life to uplift the status of the Nair community and thus founded NSS (Nair Service Society).",
    "Kirti Azad – The former cricketer is the son of former Bihar chief minister, Bhagwat Jha Azad. Azad remained active in cricket between 1980 to 86 and was part of the squad which won 1983 Cricket world cup. He’s also a Member of Parliament from Darbhanga, Bihar."]
  },{
    id : "30", 
    events : ["Bharatiya Janata Party (BJP) leader Jaswant Singh who served as minister of finance, defence and external affairs in the union cabinet was born on January 3, 1938 at Jasol village in Rajasthan’s Barmer district to Sardara Singh and Kunwar Baisa.",
    ]
  },
  {
    id : "50", 
    events : ["1066 – Edward the Confessor dies childless, sparking a succession crisis that will eventually lead to the Norman conquest of England.",
      "1477 – Battle of Nancy: Charles the Bold is killed and Burgundy becomes part of France.",
      "1500 – Duke Ludovico Sforza conquers Milan.",
      "1527 – Felix Manz, a leader of the Anabaptist congregation in Zürich, Switzerland, is executed by drowning.",
      "1554 – A great fire occurs in Eindhoven, Netherlands.",
      "1664 – Maratha forces under Chhatrapati Shivaji defeat the Mughals in the Battle of Surat.",
      "1675 – Battle of Colmar: The French army beats Brandenburg.",
      "1757 – Louis XV of France survives an assassination attempt by Robert-François Damiens, the last person to be executed in France by drawing and quartering, the traditional and gruesome form of capital punishment used for regicides.",
      "1781 – American Revolutionary War: Richmond, Virginia, is burned by British naval forces led by Benedict Arnold.",
      "1846 – The United States House of Representatives votes to stop sharing the Oregon Territory with the United Kingdom.",
      "1875 – The Palais Garnier, one of the most famous opera houses in the world, is inaugurated in Paris.",
      "1882 – Charles J. Guiteau is found guilty of assassinating US President James A. Garfield, and is sentenced to death by hanging."
   ]
  },{
    id : "60",
    events : [
"1540 – King Henry VIII of England marries Anne of Cleves.",
"1661 – English Restoration: The Fifth Monarchists unsuccessfully attempt to seize control of London, England.",
"1690 – Joseph, son of Emperor Leopold I, becomes King of the Romans.",
"1781 – In the Battle of Jersey, the British defeat the last attempt by France to invade Jersey in the Channel Islands.",
"1809 – Combined British, Portuguese and colonial Brazilian forces begin the Invasion of Cayenne during the Napoleonic Wars.",
"1838 – Alfred Vail demonstrates a telegraph system using dots and dashes (this is the forerunner of Morse code).",
"1839 – The Night of the Big Wind, the most damaging storm in 300 years, sweeps across Ireland, damaging or destroying more than 20% of the houses in Dublin.",
"1893 – The Washington National Cathedral is chartered by Congress. The charter is signed by President Benjamin Harrison.",
"1900 – Second Boer War: Having already besieged the fortress at Ladysmith, Boer forces attack it, but are driven back by British defenders.",
"1912 – New Mexico is admitted to the Union as the 47th U.S. state.",
"1912 – German geophysicist Alfred Wegener first presents his theory of continental drift.",
"1929 – King Alexander of the Serbs, Croats and Slovenes suspends his country's constitution (the January 6th Dictatorship).",
"1929 – Mother Teresa arrives in Calcutta, India, to begin her work among India's poorest and sick people.",
"1930 – The first diesel-powered automobile trip is completed, from Indianapolis, Indiana, to New York, New York.",
"1931 – Thomas Edison signs his last patent application.",
"1941 – United States President Franklin D. Roosevelt delivers his Four Freedoms speech in the State of the Union address.",
"1946 – The first general election ever in Vietnam is held.",
"1947 – Pan American Airlines becomes the first commercial airline to offer a round-the-world ticket.",
"1949– General Su Yu, deputy commander of the communist Third Field Army, launched final offensive against nationalist forces south of Xuzhou, Huaihai Campaign ends four days later.",
"1950 – The United Kingdom recognizes the People's Republic of China. The Republic of China severs diplomatic relations with the UK in response.",
"1951 – Korean War: An estimated 200–1,300 South Korean communist sympathizers are slaughtered in what becomes the Ganghwa massacre.",
"1960 – National Airlines Flight 2511 is destroyed in mid-air by a bomb, while en route from New York City to Miami.",
"1960 – The Associations Law comes into force in Iraq, allowing registration of political parties.",
"1967 – Vietnam War: United States Marine Corps and ARVN troops launch Operation Deckhouse Five in the Mekong River delta.",
"1974 – In response to the 1973 oil crisis, daylight saving time commences nearly four months early in the United States.",
"1978 – The Crown of St. Stephen (also known as the Holy Crown of Hungary) is returned to Hungary from the United States, where it was held after World War II.",
"1989 – Satwant Singh and Kehar Singh are sentenced to death for conspiracy in the assassination of Prime Minister Indira Gandhi; the two men are executed the same day.",
"1992 – President of Georgia Zviad Gamsakhurdia flees the country as a result of the military coup.",
"1995 – A chemical fire in an apartment complex in Manila, Philippines, leads to the discovery of plans for Project Bojinka, a mass-terrorist attack.",
"2001 – The US Congress certifies George W. Bush winner of 2000 presidential election.",
"2005 – American Civil Rights Movement: Edgar Ray Killen is arrested as a suspect in the 1964 murders of Chaney, Goodman, and Schwerner.",
"2005 – A train collision in Graniteville, South Carolina, releases about 60 tons of chlorine gas.",
"2012 – Twenty-six people are killed and 63 wounded when a suicide bomber blows himself up at a police station in Damascus.",
"2017 – Five people are killed and six others injured in a mass shooting at Fort Lauderdale–Hollywood International Airport in Broward County, Florida.",
"2017 – The US Congress certifies Donald Trump winner of 2016 presidential election."
    ]
  },{
    id : "70",
    events : [
      "1131 – Canute Lavard was murdered at Haraldsted, Denmark by his cousin, Magnus I of Sweden.",
      "1325 – Alfonso IV becomes King of Portugal.",
      "1558 – French troops, led by Francis, Duke of Guise, take Calais, the last continental possession of England.",
      "1566 – Pope Pius V is elected.",
      "1608 – Fire destroys Jamestown, Virginia.",
      "1610 – Galileo Galilei makes his first observation of the four Galilean moons: Ganymede, Callisto, Io and Europa, although he is not able to distinguish the last two until the following day.",
      "1738 – A peace treaty is signed between Peshwa Bajirao and Jai Singh II following Maratha victory in the Battle of Bhopal.",
      "1782 – The first American commercial bank, the Bank of North America, opens.",
      "1785 – Frenchman Jean-Pierre Blanchard and American John Jeffries travel from Dover, England, to Calais, France, in a gas balloon.",
      "1835 – HMS Beagle drops anchor off the Chonos Archipelago.",
      "1894 – William Kennedy Dickson receives a patent for motion picture film.",
      "1904 – The distress signal CQD is established only to be replaced two years later by SOS.",
      "1919 – Montenegrin guerrilla fighters rebel against the planned annexation of Montenegro by Serbia, but fail.",
      "1920 – The New York State Assembly refuses to seat five duly elected Socialist assemblymen.",
      "1922 – Dáil Éireann ratifies the Anglo-Irish Treaty by a 64–57 vote.",
      "1927 – The first transatlantic telephone service is established from New York City to London.",
      "1928 – A disastrous flood of the River Thames kills 14 people and causes extensive damage to much of riverside London.",
      "1931 – Guy Menzies flies the first solo non-stop trans-Tasman flight (from Australia to New Zealand) in 11 hours and 45 minutes, crash-landing on New Zealand's west coast.",
      "1935 – Benito Mussolini and French Foreign minister Pierre Laval sign the Franco-Italian Agreement.",
      "1939 – Marguerite Perey discovers Francium, the last element first discovered in nature, rather than by synthesis.",
      "1940 – Winter War: The Finnish 9th Division stop and completely destroy the numerically superior Soviet forces on the Raate-Suomussalmi road.",
      "1942 – World War II: The siege of the Bataan Peninsula begins.",
      "1945 – World War II: British General Bernard Montgomery holds a press conference in which he claims credit for victory in the Battle of the Bulge.",
      "1948 – Kentucky Air National Guard pilot Thomas Mantell crashes while in pursuit of a supposed UFO.",
      "1954 – Georgetown-IBM experiment: The first public demonstration of a machine translation system, is held in New York at the head office of IBM.",
      "1955 – Contralto Marian Anderson becomes the first person of color to perform at the Metropolitan Opera in Giuseppe Verdi's Un ballo in maschera.",
      "1959 – The United States recognizes the new Cuban government of Fidel Castro.",
      "1968 – Surveyor Program: Surveyor 7, the last spacecraft in the Surveyor series, lifts off from launch complex 36A, Cape Canaveral.",
      "1973 – Mark Essex fatally shoots ten people and wounds 13 others at Howard Johnson's Hotel in New Orleans, Louisiana, before being shot to death by police officers.",
      "1979 – Third Indochina War: Cambodian–Vietnamese War: Phnom Penh falls to the advancing Vietnamese troops, driving out Pol Pot and the Khmer Rouge.",
      "1980 – U.S. President Jimmy Carter authorizes legislation giving $1.5 billion in loans to bail out the Chrysler Corporation.",
      "1984 – Brunei becomes the sixth member of the Association of Southeast Asian Nations (ASEAN).",
      "1985 – Japan Aerospace Exploration Agency launches Sakigake, Japan's first interplanetary spacecraft and the first deep space probe to be launched by any country other than the United States or the Soviet Union.",
      "1991 – Roger Lafontant, former leader of the Tonton Macoute in Haiti under François Duvalier, attempts a coup d'état, which ends in his arrest.",
      "1993 – The Fourth Republic of Ghana is inaugurated with Jerry Rawlings as President.",
      "1993 – Bosnian War: The Bosnian Army executes a surprise attack at the village of Kravica in Srebrenica.",
      "1999 – The Senate trial in the impeachment of U.S. President Bill Clinton begins.",
      "2005 – Crevalcore train crash in Italy: 17 dead and dozens injured.",
      "2012 – A hot air balloon crashes near Carterton, New Zealand, killing all 11 people on board.",
      "2015 – Two gunmen commit mass murder at the offices of Charlie Hebdo in Paris, shooting twelve people execution style, and wounding eleven others.",
      "2015 – A car bomb explodes outside a police college in the Yemeni capital Sana'a with at least 38 people reported dead and more than 63 injured."
    ]
  },
 {
    id : "80",
    events : [
      "307 – Jin Huidi, Chinese emperor of the Jin Dynasty, is poisoned and succeeded by Jin Huaidi.",
      "871 – Alfred the Great leads a West Saxon army to repel an invasion by Danelaw Vikings.",
      "1297 – François Grimaldi, disguised as a monk, leads his men to capture the fortress protecting the Rock of Monaco, establishing his family as the rulers of Monaco.",
      "1499 – Louis XII of France marries Anne of Brittany in accordance with a law set by his predecessor, Charles VIII.",
      "1547 – The first Lithuanian-language book, Simple Words of Catechism, is published in Königsberg.",
      "1735 – Premiere performance of George Frideric Handel's Ariodante at the Royal Opera House, Covent Garden.",
      "1790 – George Washington delivers the first State of the Union address in New York City.",
      "1806 – Cape Colony becomes a British colony.",
      "1811 – An unsuccessful slave revolt is led by Charles Deslondes in St. Charles and St. James, Louisiana.",
      "1815 – War of 1812: Battle of New Orleans: Andrew Jackson leads American forces in victory over the British.",
      "1816 – Sophie Germain wins the Paris Academy of Sciences' Grand Prize for her mathematical work on Elasticity (physics).",
      "1835 – The United States national debt is zero for the only time.",
      "1863 – American Civil War: Second Battle of Springfield.",
      "1867 – African American men are granted the right to vote in Washington, D.C.",
      "1877 – Crazy Horse and his warriors fight their last battle against the United States Cavalry at Wolf Mountain, Montana Territory.",
      "1889 – Herman Hollerith is issued US patent #395,791 for the 'Art of Applying Statistics' — his punched card calculator.",
      "1912 – The African National Congress is founded.",
      "1918 – U.S. President Woodrow Wilson announces his Fourteen Points for the aftermath of World War I.",
      "1920 – The steel strike of 1919 ends in a complete failure for the Amalgamated Association of Iron, Steel and Tin Workers labor union.",
      "1925 – The All-Woman Supreme Court met for the first time in Texas, the first all-female supreme court in the history of the United States.",
      "1926 – Crown Prince Nguyễn Phúc Vĩnh Thuỵ ascends to the throne, the last monarch of Vietnam.",
      "1926 – Abdul-Aziz ibn Saud was crowned King of Hejaz.",
      "1936 – Kashf-e hijab decree is enforced by Reza Shah ordering the police to physically remove the Hijab from any woman in public.",
      "1940 – World War II: Britain introduces food rationing.",
      "1945 – World War II: Philippine Commonwealth troops under the Philippine Commonwealth Army units enter the province of Ilocos Sur in Northern Luzon and attack Japanese Imperial forces.",
      "1956 – Operation Auca: Five U.S. missionaries are killed by the Huaorani of Ecuador shortly after making contact with them.",
      "1961 – In France a referendum supports Charles de Gaulle's policies in Algeria.",
      "1963 – Leonardo da Vinci's Mona Lisa is exhibited in the United States for the first time, at the National Gallery of Art in Washington, D.C.",
      "1964 – President Lyndon B. Johnson declares a War on Poverty in the United States.",
      "1972 – Bowing to international pressure, President of Pakistan Zulfikar Ali Bhutto releases Bengali leader Sheikh Mujibur Rahman from prison, who had been arrested after declaring the independence of Bangladesh.",
      "1973 – Soviet space mission Luna 21 is launched.",
      "1973 – Watergate scandal: The trial of seven men accused of illegal entry into Democratic Party headquarters at Watergate begins.",
      "1975 – Ella T. Grasso becomes Governor of Connecticut, the first woman to serve as a Governor in the United States other than by succeeding her husband.",
      "1977 – Three bombs explode in Moscow, Russia, Soviet Union, within 37 minutes, killing seven. The bombings are attributed to an Armenian separatist group.",
      "1981 – A local farmer reports a UFO sighting in Trans-en-Provence, France, claimed to be perhaps the most completely and carefully documented sighting of all time.",
      "1982 – Breakup of the Bell System: AT&T agrees to divest itself of twenty-two subdivisions.",
      "1989 – Kegworth air disaster: British Midland Flight 92, a Boeing 737-400, crashes into the M1 motorway, killing 47 of the 126 people on board.",
      "1994 – Russian cosmonaut Valeri Polyakov on Soyuz TM-18 leaves for Mir. He would stay on the space station until March 22, 1995, for a record 437 days in space.",
      "1996 – An Antonov An-32 cargo aircraft crashes into a crowded market in Kinshasa, Zaire, killing up to 223 on the ground; two of six crew members are also killed.",
      "2002 – President George W. Bush signs into law the No Child Left Behind Act.",
      "2003 – Turkish Airlines Flight 634 crashes near Diyarbakır Airport, Turkey, killing the entire crew and 70 of the 75 passengers.",
      "2003 – Air Midwest Flight 5481 crashes at Charlotte-Douglas Airport, Charlotte, North Carolina, killing all 21 people on board.",
      "2004 – The RMS Queen Mary 2, the largest ocean liner ever built, is christened by her namesake's granddaughter, Queen Elizabeth II.",
      "2005 – The nuclear sub USS San Francisco collides at full speed with an undersea mountain south of Guam. One man is killed, but the sub surfaces and is repaired.",
      "2009 – A 6.1-magnitude earthquake in northern Costa Rica kills 15 people and injures 32.",
      "2010 – Gunmen from an offshoot the Front for the Liberation of the Enclave of Cabinda attack a bus carrying the Togo national football team on its way to the 2010 Africa Cup of Nations, killing three.",
      "2011 – The attempted assassination of Arizona Representative Gabrielle Giffords and subsequent shooting in Casas Adobes, Arizona, in which five people were shot dead.",
      "2016 - Joaquín Guzmán, widely regarded as the world's most powerful drug trafficker, is recaptured following his escape from a maximum security prison in Mexico."
    ]
 },{
    id : "90",
    events : [
      "475 – Byzantine Emperor Zeno is forced to flee his capital at Constantinople, and his general, Basiliscus gains control of the empire.",
      "681 – Twelfth Council of Toledo: King Erwig of the Visigoths initiates a council in which he implements diverse measures against the Jews in Spain.",
      "1127 – Jin–Song Wars: Invading Jurchen soldiers from the Jin dynasty besiege and sack Bianjing (Kaifeng), the capital of the Song dynasty of China, and abduct Emperor Qinzong of Song and others, ending the Northern Song dynasty.",
      "1150 – Wanyan Liang and other court officials murder Emperor Xizong of Jin. Wanyan Liang succeeds him as emperor.",
      "1349 – The Jewish population of Basel, believed by the residents to be the cause of the ongoing Black Death, is rounded up and incinerated.",
      "1431 – Judges' investigations for the trial of Joan of Arc begin in Rouen.",
      "1760 – Ahmad Shah Durrani defeats the Marathas in the Battle of Barari Ghat.",
      "1788 – Connecticut becomes the fifth state to ratify the Constitution.",
      "1792 – Treaty of Jassy between Russian and Ottoman Empire is signed.",
      "1793 – Jean-Pierre Blanchard becomes the first person to fly in a balloon in the United States.",
      "1799 – British Prime Minister William Pitt the Younger introduces an income tax of two shillings to the pound to raise funds for Great Britain's war effort in the Napoleonic Wars.",
      "1806 – Admiral Horatio Lord Nelson receives a state funeral and is interred in St Paul's Cathedral.",
      "1816 – Sir Humphry Davy tests his safety lamp for miners at Hebburn Colliery.",
      "1822 – The Portuguese prince Pedro I of Brazil decides to stay in Brazil against the orders of the Portuguese King João VI, beginning the Brazilian independence process.",
      "1839 – The French Academy of Sciences announces the Daguerreotype photography process.",
      "1857 – The 7.9 Mw  Fort Tejon earthquake shakes Central and Southern California with a maximum Mercalli intensity of IX (Violent).",
      "1858 – Anson Jones, the last President of the Republic of Texas, commits suicide.",
      "1861 – American Civil War: Star of the West incident occurs near Charleston, South Carolina.",
      "1861 – Mississippi becomes the second state to secede from the Union before the outbreak of the American Civil War.",
      "1878 – Umberto I becomes King of Italy.",
      "1894 – New England Telephone and Telegraph installs the first battery-operated telephone switchboard in Lexington, Massachusetts.",
      "1903 – Hallam Tennyson, 2nd Baron Tennyson, son of the poet Alfred Tennyson, becomes the second Governor-General of Australia.",
      "1909 – Ernest Shackleton, leading the Nimrod Expedition to the South Pole, plants the British flag 97 nautical miles (180 km; 112 mi) from the South Pole, the farthest anyone had ever reached at that time.",
      "1914 – Phi Beta Sigma Fraternity Inc., the first historically black intercollegiate Greek-letter fraternity to be officially recognized at Howard University, is founded.",
      "1916 – World War I: The Battle of Gallipoli concludes with an Ottoman Empire victory when the last Allied forces are evacuated from the peninsula.",
      "1917 – World War I: The Battle of Rafa is fought near the Egyptian border with Palestine.",
      "1918 – Battle of Bear Valley: The last battle of the American Indian Wars.",
      "1921 – Greco-Turkish War: The First Battle of İnönü, the first battle of the war, begins near Eskişehir in Anatolia.",
      "1923 – Juan de la Cierva makes the first autogyro flight.",
      "1923 – Lithuanian residents of the Memel Territory rebel against the League of Nations' decision to leave the area as a mandated region under French control.",
      "1927 – A fire at the Laurier Palace movie theatre in Montreal, Quebec, Canada, kills 78 children.",
      "1941 – World War II: First flight of the Avro Lancaster.",
      "1945 – World War II: The Sixth United States Army begins the invasion of Lingayen Gulf.",
      "1957 – British Prime Minister Sir Anthony Eden resigns from office following his failure to retake the Suez Canal from Egyptian sovereignty.",
      "1960 – President of Egypt Gamal Abdel Nasser opens construction on the Aswan Dam by detonating ten tons of dynamite to demolish twenty tons of granite on the east bank of the Nile.",
      "1961 – British authorities announce they have uncovered the Soviet Portland Spy Ring in London.",
      "1964 – Martyrs' Day: Several Panamanian youths try to raise the Panamanian flag in the U.S.-controlled Panama Canal Zone, leading to fighting between U.S. military and Panamanian civilians.",
      "1965 – The Mirzapur Cadet College formally opens for academic activities in East Pakistan (now Bangladesh).",
      "1991 – Representatives from the United States and Iraq meet at the Geneva Peace Conference to try to find a peaceful resolution to the Iraqi invasion of Kuwait.",
      "1992 – The Assembly of the Serb People in Bosnia and Herzegovina proclaims the creation of Republika Srpska, a new state within Yugoslavia.",
      "1992 – The first discoveries of extrasolar planets are announced by astronomers Aleksander Wolszczan and Dale Frail. They discovered two planets orbiting the pulsar PSR 1257+12.[1]",
      "1996 – First Chechen War: Chechen separatists launch a raid against the helicopter airfield and later a civilian hospital in the city of Kizlyar in the neighboring Dagestan, which turns into a massive hostage crisis involving thousands of civilians.",
      "2004 – An inflatable boat carrying illegal Albanian emigrants stalls near the Karaburun Peninsula en route to Brindisi, Italy; exposure to the elements kills 28. This is the second deadliest marine disaster in Albanian history.",
      "2005 – Mahmoud Abbas wins the election to succeed Yasser Arafat as President of the Palestinian National Authority, replacing interim president Rawhi Fattouh.",
      "2005 – The Sudan People's Liberation Movement and the Government of Sudan sign the Comprehensive Peace Agreement to end the Second Sudanese Civil War.",
      "2007 – Apple CEO Steve Jobs introduces the original iPhone at a Macworld keynote in San Francisco.",
      "2011 – Iran Air Flight 277 crashes near Orumiyeh in the northwest of the country, killing 77 people.",
      "2014 – An explosion at a Mitsubishi Materials chemical plant in Yokkaichi, Japan, kills at least five people and injures 17 others.",
      "2015 – The perpetrators of the Charlie Hebdo shooting in Paris two days earlier are both killed after a hostage situation; a second hostage situation, related to the Charlie Hebdo shooting, occurs at a Jewish market in Vincennes.",
      "2019 – The new host for the 2019 Africa Cup of Nations will be chosen in Dakar, Senegal."
    ]
  },{ 
  id : "100",
  events : [
"49 BC – Julius Caesar crosses the Rubicon, signalling the start of civil war",
"AD 9 – The Western Han dynasty ends when Wang Mang claims that the divine Mandate of Heaven called for the end of the dynasty and the beginning of his own, the Xin dynasty",
"AD 69 – Lucius Calpurnius Piso Licinianus is appointed by Galba as deputy Roman Emperor",
"236 – Pope Fabian succeeds Anterus to become the twentieth pope of Rome",
"1072 – Robert Guiscard conquers Palermo in Sicily",
"1430 – Philip the Good, the Duke of Burgundy, establishes the Order of the Golden Fleece, the most prestigious, exclusive, and expensive order of chivalry in the world",
"1475 – Stephen III of Moldavia defeats the Ottoman Empire at the Battle of Vaslui",
"1645 – Archbishop William Laud is beheaded for treason at the Tower of London",
"1776 – American Revolution : Thomas Paine publishes his pamphlet Common Sense",
"1791 – The Siege of Dunlap's Station begins near Cincinnati during the Northwest Indian War",
"1806 – Two British brigades occupy Cape Town after the Battle of Blaauwberg",
"1812 – The first steamboat on the Ohio River or the Mississippi River arrives in New Orleans, 82 days after departing from Pittsburgh",
"1861 – American Civil War: Florida becomes the third state to secede from the Union",
"1863 – The Metropolitan Railway, the world's oldest underground railway, opens between Paddington and Farringdon, marking the beginning of the London Underground",
"1870 – John D. Rockefeller incorporates Standard Oil",
"1901 – The first great Texas oil gusher is discovered at Spindletop in Beaumont, Texas",
"1916 – World War I: In the Erzurum Offensive, Russia defeats the Ottoman Empire",
"1917 – The Silent Sentinels begin their protest outside the White House, demanding suffrage for women. They continue until June 1919",
"1920 – The Treaty of Versailles takes effect, officially ending World War I",
"1920 – League of Nations Covenant enters into force. On January 16 the organization holds its first council meeting, in Paris",
"1927 – Fritz Lang's futuristic film Metropolis is released in Germany",
"1941 – World War II: The Greek army captures Kleisoura",
"1946 – The first General Assembly of the United Nations opens in London .Fifty-one nations are represented",
"1946 – The United States Army Signal Corps successfully conducts Project Diana, bouncing radio waves off the Moon and receiving the reflected signals",
"1954 – BOAC Flight 781, a de Havilland DH-106 Comet 1, explodes and falls into the Tyrrhenian Sea killing 35 people",
"1962 – Apollo program: NASA announces plans to build the C-5 rocket launch vehicle, which became known as the Saturn V Moon rocket, which launched every Apollo Moon mission",
"1966 – Tashkent Declaration, a peace agreement between India and Pakistan signed that resolved the Indo-Pakistani War of 1965",
"1972 – Sheikh Mujibur Rahman returns to the newly independent Bangladesh as president after spending over nine months in prison in Pakistan",
"1981 – Salvadoran Civil War: The FMLN launches its first major offensive, gaining control of most of Morazán and Chalatenango departments1984 – Holy See–United States relations: The United States and Holy See (Vatican City) re-establish full diplomatic relations after almost 117 years, overturning the United States Congress's 1867 ban on public funding for such a diplomatic envoy",
"1985 – Sandinista Daniel Ortega becomes president of Nicaragua and vows to continue the transformation to socialism and alliance with the Soviet Union and Cuba; American policy continues to support the Contras in their revolt against the Nicaraguan government",
"1990 – Time Warner is formed by the merger of Time Inc and Warner Communications",
"2007 – A general strike begins in Guinea in an attempt to get President Lansana Conté to resign",
"2012 – A bombing in Khyber Agency, Pakistan, kills at least 30 people and 78 others injured",
"2013 – More than 100 people are killed and 270 injured in several bomb blasts in Pakistan",
"2015 – A traffic accident between an oil tanker truck and passenger coach en route to Shikarpur from Karachi on the Pakistan National Highway Link Road near Gulshan-e-Hadeed, Karachi, killing at least 62 people"
  ]  
},{
  id:"110",
  events : [
    "532 – Nika riots in Constantinople: A quarrel between supporters of different chariot teams—the Blues and the Greens—in the Hippodrome escalates into violence.",
    "630 – Conquest of Mecca: The prophet Muhammad and his followers conquer the city, Quraysh surrender.",
    "947 – Emperor Tai Zong of the Khitan-led Liao Dynasty invades the Later Jin, resulting in the destruction of the Later Jin.",
    "1055 – Theodora is crowned empress of the Byzantine Empire.",
    "1158 – Vladislaus II, Duke of Bohemia becomes King of Bohemia.",
    "1569 – First recorded lottery in England.",
    "1571 – Austrian nobility is granted freedom of religion.",
    "1693 – A powerful earthquake destroys parts of Sicily and Malta.",
    "1759 – In Philadelphia, Pennsylvania, the first American life insurance company is incorporated.",
    "1779 – Ching-Thang Khomba is crowned King of Manipur.",
    "1787 – William Herschel discovers Titania and Oberon, two moons of Uranus.",
    "1805 – The Michigan Territory is created.",
    "1861 – American Civil War : Alabama secedes from the United States.",
    "1863 – American Civil War: Battle of Arkansas Post: General John McClernand and Admiral David Dixon Porter capture the Arkansas River for the Union.",
    "1863 – American Civil War: CSS Alabama encounters and sinks the USS Hatteras off Galveston Lighthouse in Texas.",
    "1879 – The Anglo-Zulu War begins.",
    "1908 – Grand Canyon National Monument is created.",
    "1912 – Immigrant textile workers in Lawrence, Massachusetts, go on strike when wages are reduced in response to a mandated shortening of the work week.",
    "1917 – The Kingsland munitions factory explosion occurs as a result of sabotage.",
    "1922 – First use of insulin to treat diabetes in a human patient.",
    "1923 – Occupation of the Ruhr: Troops from France and Belgium occupy the Ruhr area to force Germany to make its World War I reparation payments.",
    "1927 – Louis B. Mayer, head of film studio Metro-Goldwyn-Mayer (MGM), announces the creation of the Academy of Motion Picture Arts and Sciences, at a banquet in Los Angeles, California.",
    "1935 – Amelia Earhart becomes the first person to fly solo from Hawaii to California.",
    "1942 – World War II: The Japanese capture Kuala Lumpur, the capital of the Federated Malay States.",
    "1942 – World War II: The Japanese attack Tarakan in Borneo, Netherlands Indies (Battle of Tarakan)",
    "1943 – The Republic of China agrees to the Sino-British New Equal Treaty and the Sino-American New Equal Treaty.",
    "1943 – Italian-American anarchist Carlo Tresca is assassinated in New York City.",
    "1946 – Enver Hoxha, Secretary General of the Communist Party of Albania, declares the People's Republic of Albania with himself as head of state.",
    "1949 – The first 'networked' television broadcasts took place as KDKA-TV in Pittsburgh, Pennsylvania goes on the air connecting the east coast and mid-west programming.",
    "1957 – The African Convention is founded in Dakar, Senegal.",
    "1961 – Throgs Neck Bridge over the East River, linking New York City's boroughs of The Bronx and Queens, opens to road traffic.",
    "1962 – Cold War: While tied to its pier in Polyarny, the Soviet submarine B-37 is destroyed when fire breaks out in its torpedo compartment.",
    "1962 – An avalanche on Huascarán in Peru causes around 4,000 deaths.",
    "1964 – Surgeon General of the United States Dr. Luther Terry, M.D., publishes the landmark report Smoking and Health: Report of the Advisory Committee to the Surgeon General of the United States saying that smoking may be hazardous to health, sparking national and worldwide anti-smoking efforts.",
    "1972 – East Pakistan renames itself Bangladesh.",
    "1973 – Major League Baseball owners vote in approval of the American League adopting the designated hitter position.",
    "1986 – The Gateway Bridge, Brisbane, Queensland, Australia is officially opened.",
    "1994 – The Irish Government announces the end of a 15-year broadcasting ban on the IRA and its political arm Sinn Féin.",
    "1996 – Space Shuttle program: STS-72 launches from the Kennedy Space Center marking the start of the 74th Space Shuttle mission and the 10th flight of Endeavour.",
    "1996 - Ryutaro Hashimoto, leader of the Liberal Democratic Party, becomes Prime Minister of Japan.",
    "1998 – Over 100 people are killed in the Sidi-Hamed massacre in Algeria.",
    "2003 – Illinois Governor George Ryan commutes the death sentences of 167 prisoners on Illinois's death row based on the Jon Burge scandal.",
    "2013 – One French soldier and 17 militants are killed in a failed attempt to free a French hostage in Bulo Marer, Somalia."
  ]
},{
  id: "120",
  events : [
"1528 – Gustav I of Sweden is crowned King of Sweden, having already reigned since his election in June 1523.",
"1554 – Bayinnaung, who would go on to assemble the largest empire in the history of Southeast Asia, is crowned King of Burma.",
"1616 – The city of Belém, Brazil is founded on the Amazon River delta, by Portuguese captain Francisco Caldeira Castelo Branco.",
"1808 – John Rennie's scheme to defend St Mary's Church, Reculver, founded in 669, from coastal erosion is abandoned in favour of demolition, despite the church being an exemplar of Anglo-Saxon architecture and sculpture.",
"1808 – The organizational meeting leading to the creation of the Wernerian Natural History Society, a former Scottish learned society, is held in Edinburgh.",
"1848 – The Palermo rising takes place in Sicily against the Bourbon Kingdom of the Two Sicilies.",
"1866 – The Royal Aeronautical Society is formed in London.",
"1872 – Yohannes IV is crowned Emperor of Ethiopia in Axum, the first imperial coronation in that city in over 200 years.",
"1895 – The National Trust is founded in the United Kingdom.",
"1908 – A long-distance radio message is sent from the Eiffel Tower for the first time.",
"1911 – The University of the Philippines College of Law is formally established; three future Philippine presidents are among the first enrollees.",
"1915 – The United States House of Representatives rejects a proposal to require states to give women the right to vote.",
"1916 – Both Oswald Boelcke and Max Immelmann, for achieving eight aerial victories each over Allied aircraft, receive the German Empire's highest military award, the Pour le Mérite as the first German aviators to earn it.",
"1918 – The Minnie Pit Disaster coal mining accident occurs in Halmer End, Staffordshire, in which 155 men and boys die.",
"1921 – Acting to restore confidence in baseball after the Black Sox Scandal, Judge Kenesaw Mountain Landis is elected as Major League Baseball's first commissioner.",
"1932 – Hattie Caraway becomes the first woman elected to the United States Senate.",
"1942 – World War II: United States President Franklin D. Roosevelt creates the National War Labor Board.",
"1945 – World War II: The Red Army begins the Vistula–Oder Offensive.",
"1962 – Vietnam War: Operation Chopper, the first American combat mission in the war, takes place.",
"1964 – Rebels in Zanzibar begin a revolt known as the Zanzibar Revolution and proclaim a republic.",
"1966 – Lyndon B. Johnson states that the United States should stay in South Vietnam until Communist aggression there is ended.",
"1967 – Dr. James Bedford becomes the first person to be cryonically preserved with intent of future resuscitation.",
"1969 – The New York Jets of the American Football League defeat the Baltimore Colts of the National Football League to win Super Bowl III in what is considered to be one of the greatest upsets in sports history.",
"1970 – Biafra capitulates, ending the Nigerian Civil War.",
"1971 – The Harrisburg Seven: Rev. Philip Berrigan and five other activists are indicted on charges of conspiring to kidnap Henry Kissinger and of plotting to blow up the heating tunnels of federal buildings in Washington, D.C.",
"1976 – The United Nations Security Council votes 11–1 to allow the Palestine Liberation Organization to participate in a Security Council debate (without voting rights).",
"1986 – Space Shuttle program: Congressman Bill Nelson lifts off from Kennedy Space Center aboard Columbia on mission STS-61-C as a payload specialist.",
"1990 – A seven-day pogrom breaks out against the Armenian civilian population of Baku, Azerbaijan, during which Armenians were beaten, tortured, murdered, and expelled from the city.",
"1991 – Persian Gulf War: An act of the U.S. Congress authorizes the use of American military force to drive Iraq out of Kuwait.",
"1998 – Nineteen European nations agree to forbid human cloning.",
"2001 – Downtown Disney opens to the public as part of the Disneyland Resort in Anaheim, California.",
"2004 – The world's largest ocean liner, RMS Queen Mary 2, makes its maiden voyage.",
"2005 – Deep Impact launches from Cape Canaveral on a Delta II rocket.",
"2006 – A stampede during the Stoning of the Devil ritual on the last day at the Hajj in Mina, Saudi Arabia, kills at least 362 Muslim pilgrims.",
"2010 – An earthquake in Haiti occurs, killing over 100,000 people and destroying much of the capital Port-au-Prince.",
"2012 – Violent protests occur in Bucharest, Romania, as two-day-old demonstrations continue against President Traian Băsescu's economic austerity measures. Clashes are reported in numerous Romanian cities between protesters and law enforcement officers.",
"2015 – Government raids kill 143 Boko Haram fighters in Kolofata, Cameroon.",
"2016 – Ten people are killed and 15 wounded in a bombing near the Blue Mosque in Istanbul."
  ]
},{
  id:"130",
  events:[
    "532 – Nika riots in Constantinople.",
    "1435 – Sicut Dudum, forbidding the enslavement of the Guanche natives in Canary Islands by the Spanish, is promulgated by Pope Eugene IV.",
    "1547 – Henry Howard, Earl of Surrey is sentenced to death.",
    "1607 – The Bank of Genoa fails after announcement of national bankruptcy in Spain.",
    "1793 – Nicolas Jean Hugon de Bassville, representative of Revolutionary France, lynched by a mob in Rome",
    "1797 – French Revolutionary Wars: A naval battle between a French ship of the line and two British frigates off the coast of Brittany ends with the French vessel running aground, resulting in over 900 deaths.",
    "1815 – War of 1812: British troops capture Fort Peter in St. Marys, Georgia, the only battle of the war to take place in the state.",
    "1822 – The design of the Greek flag is adopted by the First National Assembly at Epidaurus.",
    "1830 – The Great Fire of New Orleans begins.",
    "1833 – United States President Andrew Jackson writes to Vice President Martin Van Buren expressing his opposition to South Carolina's defiance of federal authority in the Nullification Crisis.",
    "1840 – The steamship Lexington burns and sinks four miles off the coast of Long Island with the loss of 139 lives.",
    "1842 – Dr. William Brydon, an assistant surgeon in the British East India Company Army during the First Anglo-Afghan War, becomes famous for being the sole survivor of an army of 4,500 men and 12,000 camp followers when he reaches the safety of a garrison in Jalalabad, Afghanistan.",
    "1847 – The Treaty of Cahuenga ends the Mexican–American War in California.",
    "1849 – Establishment of the Colony of Vancouver Island.",
    "1849 – Second Anglo-Sikh War – Battle of Tooele: British forces retreat from the Sikhs.",
    "1879 – In Mozart Gardens Brooklyn Ada Anderson completed a great feat of pedestrianism - 2700 quarter miles in 2700 quarter hours, earning her $8000.",
    "1888 – The National Geographic Society is founded in Washington, D.C.",
    "1893 – The Independent Labour Party of the United Kingdom holds its first meeting.",
    "1893 – U.S. Marines land in Honolulu, Hawaii from the USS Boston to prevent the queen from abrogating the Bayonet Constitution.",
    "1895 – First Italo-Ethiopian War: the war's opening battle, the Battle of Coatit, occurs; it is an Italian victory.",
    "1898 – Émile Zola's J'accuse…! exposes the Dreyfus affair.",
    "1908 – The Rhoads Opera House fire in Boyertown, Pennsylvania kills 171 people.",
    "1910 – The first public radio broadcast takes place; a live performance of the operas Cavalleria rusticana and Pagliacci are sent out over the airwaves from the Metropolitan Opera House in New York.",
    "1915 – The 6.7 Mw  Avezzano earthquake shakes the Province of L'Aquila in Italy with a maximum Mercalli intensity of XI (Extreme), killing between 29,978–32,610.",
    "1935 – A plebiscite in Saarland shows that 90.3% of those voting wish to join Nazi Germany.",
    "1939 – The Black Friday bushfires burn 20,000 square kilometers of land in Australia, claiming the lives of 71 people.",
    "1942 – Henry Ford patents a plastic automobile, which is 30% lighter than a regular car.",
    "1942 – World War II: First use of an aircraft ejection seat by a German test pilot in a Heinkel He 280 jet fighter.",
    "1942 – Tuan Syed Hamzah Jamalullail was proclaimed as Raja Muda of Perlis by Japan's highest government.",
    "1950 – British submarine HMS Truculent collides with an oil tanker in the Thames Estuary, killing 64 men.",
    "1950 – Finland forms diplomatic relations with the People's Republic of China.",
    "1951 – First Indochina War: The Battle of Vĩnh Yên begins.",
    "1953 – An article appears in Pravda accusing some of the most prestigious and prominent doctors, mostly Jews, in the Soviet Union of taking part in a vast plot to poison members of the top Soviet political and military leadership.",
    "1958 – The Moroccan Army of Liberation ambushes a Spanish patrol in the Battle of Edchera.",
    "1963 – Coup d'état in Togo results in the assassination of president Sylvanus Olympio.",
    "1964 – Riots break out in Calcutta, resulting in 100 deaths.",
    "1964 – In Manchester, New Hampshire, fourteen-year-old Pamela Mason is murdered. Edward Coolidge is tried and convicted of the crime, but the conviction is set aside by the landmark Fourth Amendment case Coolidge v. New Hampshire (1971).",
    "1966 – Robert C. Weaver becomes the first African American Cabinet member when he is appointed United States Secretary of Housing and Urban Development.",
    "1968 – Johnny Cash performs live at Folsom State Prison.",
    "1972 – Prime Minister Kofi Abrefa Busia and President Edward Akufo-Addo of Ghana are ousted in a bloodless military coup by Colonel Ignatius Kutu Acheampong.",
    "1972 – Bernice Gera wins her five year discrimination case against the US National Association of Baseball Leagues, opening up baseball umpiring to women.",
    "1974 – Seraphim is elected Archbishop of Athens and All Greece.",
    "1976 – Sarah Caldwell becomes the first woman to conduct an opera, La traviata, at the Metropolitan Opera.",
    "1978 – United States Food and Drug Administration requires all blood donations to be labeled 'paid' or 'volunteer' donors.",
    "1982 – Shortly after takeoff, Air Florida Flight 90, a Boeing 737 jet, crashes into Washington, D.C.'s 14th Street Bridge and falls into the Potomac River, killing 78 including four motorists.",
    "1985 – A passenger train plunges into a ravine in Ethiopia, killing 428 in the worst railroad disaster in Africa.",
    "1986 – A month-long violent struggle begins in Aden, South Yemen between supporters of Ali Nasir Muhammad and Abdul Fattah Ismail, resulting in thousands of casualties.",
    "1988 – Lee Teng-hui becomes the first native Taiwanese President of the Republic of China.",
    "1990 – Douglas Wilder becomes the first elected African American governor as he takes office in Richmond, Virginia.",
    "1991 – Soviet Union troops attack Lithuanian independence supporters in Vilnius, killing 14 people and wounding around 1000 others.",
    "1993 – Space Shuttle program: Endeavour heads for space for the third time as STS-54 launches from the Kennedy Space Center.",
    "1993 – The Chemical Weapons Convention (CWC) is signed.",
    "1998 – Alfredo Ormando sets himself on fire in St. Peter's Square, protesting against homophobia.",
    "2001 – An earthquake hits El Salvador, killing more than 800.",
    "2002 – A wild fox wanders into the United States Supreme Court Building and evades capture for more than a day despite being spotted by a police officer and observed on video cameras.",
    "2012 – The passenger cruise ship Costa Concordia sinks off the coast of Italy due to the captain Francesco Schettino's negligence and irresponsibility. There are 32 confirmed deaths.",
    "2018 – The killing of Naqeebullah Mehsud in a fake encounter staged by the police officer Rao Anwar in Karachi, Pakistan sparked countrywide protests against extrajudicial killings. The Pashtun Tahafuz Movement (Pashtun Protection Movement), led by Manzoor Pashteen, launched a campaign to seek justice for Naqeebullah Mehsud.",
    "2018 – A false emergency alert warning of an impending missile strike in Hawaii caused widespread panic in the state."
  ]
}
];
  module.exports=ob ;