 var ob = [
  {
    id : "2911",
    events : ["1929 - On 31 December 1929, Congress passed the historic resolution declaring Purna Swaraj as its goal.",
        "1922-Birth of Swaraj Party - Chittaranjan Das - President - Motilal Nehru - Secretary",
    "1600-East India Company was given the Royal charter"]  
  },
  {
    id : "3111",
    events : ["1929 - On 31 December 1929, Congress passed the historic resolution declaring Purna Swaraj as its goal.",
        "1922-Birth of Swaraj Party - Chittaranjan Das - President - Motilal Nehru - Secretary",
    "1600-East India Company was given the Royal charter"]  
  },
  {
    id : "3011", 
    events : ["In the year 1877, Queen Victoria of the erstwhile British Empire is proclaimed the Empress of India.",
    "During the 1949 war with Pakistan – Prime Minister approached United Nations against the armed insurgency by Pakistan. According to an UN decree, a cease-fire took effect on this date and the war between the two countries stopped and a status-quo was maintained thereafter."]
  },{
    id : "20", 
    events : ["A 1975 bomb blast at Samastipur, Bihar fatally wounded the then Minister of Railways, Lalit Narayan Mishra. The sessions court gave a verdict in a trial after 39 years which convicted 5 accused of secretly plotting and murdering the minister and 3 others. The verdict was later quashed by the high court and all of accused were acquitted.",
    "Mannathu Padnabha Pillai – The social reformer and freedom fighter from the state of Kerala was born in 1878 in the erstwhile princely state of Travancore. He dedicated his life to uplift the status of the Nair community and thus founded NSS (Nair Service Society).",
    "Kirti Azad – The former cricketer is the son of former Bihar chief minister, Bhagwat Jha Azad. Azad remained active in cricket between 1980 to 86 and was part of the squad which won 1983 Cricket world cup. He’s also a Member of Parliament from Darbhanga, Bihar."]
  },{
    id : "30", 
    events : ["Bharatiya Janata Party (BJP) leader Jaswant Singh who served as minister of finance, defence and external affairs in the union cabinet was born on January 3, 1938 at Jasol village in Rajasthan’s Barmer district to Sardara Singh and Kunwar Baisa.",
    ]
  },
  {
    id : "50", 
    events : ["1066 – Edward the Confessor dies childless, sparking a succession crisis that will eventually lead to the Norman conquest of England.",
      "1477 – Battle of Nancy: Charles the Bold is killed and Burgundy becomes part of France.",
      "1500 – Duke Ludovico Sforza conquers Milan.",
      "1527 – Felix Manz, a leader of the Anabaptist congregation in Zürich, Switzerland, is executed by drowning.",
      "1554 – A great fire occurs in Eindhoven, Netherlands.",
      "1664 – Maratha forces under Chhatrapati Shivaji defeat the Mughals in the Battle of Surat.",
      "1675 – Battle of Colmar: The French army beats Brandenburg.",
      "1757 – Louis XV of France survives an assassination attempt by Robert-François Damiens, the last person to be executed in France by drawing and quartering, the traditional and gruesome form of capital punishment used for regicides.",
      "1781 – American Revolutionary War: Richmond, Virginia, is burned by British naval forces led by Benedict Arnold.",
      "1846 – The United States House of Representatives votes to stop sharing the Oregon Territory with the United Kingdom.",
      "1875 – The Palais Garnier, one of the most famous opera houses in the world, is inaugurated in Paris.",
      "1882 – Charles J. Guiteau is found guilty of assassinating US President James A. Garfield, and is sentenced to death by hanging."
   ]
  },{
    id : "60",
    events : [
"1540 – King Henry VIII of England marries Anne of Cleves.",
"1661 – English Restoration: The Fifth Monarchists unsuccessfully attempt to seize control of London, England.",
"1690 – Joseph, son of Emperor Leopold I, becomes King of the Romans.",
"1781 – In the Battle of Jersey, the British defeat the last attempt by France to invade Jersey in the Channel Islands.",
"1809 – Combined British, Portuguese and colonial Brazilian forces begin the Invasion of Cayenne during the Napoleonic Wars.",
"1838 – Alfred Vail demonstrates a telegraph system using dots and dashes (this is the forerunner of Morse code).",
"1839 – The Night of the Big Wind, the most damaging storm in 300 years, sweeps across Ireland, damaging or destroying more than 20% of the houses in Dublin.",
"1893 – The Washington National Cathedral is chartered by Congress. The charter is signed by President Benjamin Harrison.",
"1900 – Second Boer War: Having already besieged the fortress at Ladysmith, Boer forces attack it, but are driven back by British defenders.",
"1912 – New Mexico is admitted to the Union as the 47th U.S. state.",
"1912 – German geophysicist Alfred Wegener first presents his theory of continental drift.",
"1929 – King Alexander of the Serbs, Croats and Slovenes suspends his country's constitution (the January 6th Dictatorship).",
"1929 – Mother Teresa arrives in Calcutta, India, to begin her work among India's poorest and sick people.",
"1930 – The first diesel-powered automobile trip is completed, from Indianapolis, Indiana, to New York, New York.",
"1931 – Thomas Edison signs his last patent application.",
"1941 – United States President Franklin D. Roosevelt delivers his Four Freedoms speech in the State of the Union address.",
"1946 – The first general election ever in Vietnam is held.",
"1947 – Pan American Airlines becomes the first commercial airline to offer a round-the-world ticket.",
"1949– General Su Yu, deputy commander of the communist Third Field Army, launched final offensive against nationalist forces south of Xuzhou, Huaihai Campaign ends four days later.",
"1950 – The United Kingdom recognizes the People's Republic of China. The Republic of China severs diplomatic relations with the UK in response.",
"1951 – Korean War: An estimated 200–1,300 South Korean communist sympathizers are slaughtered in what becomes the Ganghwa massacre.",
"1960 – National Airlines Flight 2511 is destroyed in mid-air by a bomb, while en route from New York City to Miami.",
"1960 – The Associations Law comes into force in Iraq, allowing registration of political parties.",
"1967 – Vietnam War: United States Marine Corps and ARVN troops launch Operation Deckhouse Five in the Mekong River delta.",
"1974 – In response to the 1973 oil crisis, daylight saving time commences nearly four months early in the United States.",
"1978 – The Crown of St. Stephen (also known as the Holy Crown of Hungary) is returned to Hungary from the United States, where it was held after World War II.",
"1989 – Satwant Singh and Kehar Singh are sentenced to death for conspiracy in the assassination of Prime Minister Indira Gandhi; the two men are executed the same day.",
"1992 – President of Georgia Zviad Gamsakhurdia flees the country as a result of the military coup.",
"1995 – A chemical fire in an apartment complex in Manila, Philippines, leads to the discovery of plans for Project Bojinka, a mass-terrorist attack.",
"2001 – The US Congress certifies George W. Bush winner of 2000 presidential election.",
"2005 – American Civil Rights Movement: Edgar Ray Killen is arrested as a suspect in the 1964 murders of Chaney, Goodman, and Schwerner.",
"2005 – A train collision in Graniteville, South Carolina, releases about 60 tons of chlorine gas.",
"2012 – Twenty-six people are killed and 63 wounded when a suicide bomber blows himself up at a police station in Damascus.",
"2017 – Five people are killed and six others injured in a mass shooting at Fort Lauderdale–Hollywood International Airport in Broward County, Florida.",
"2017 – The US Congress certifies Donald Trump winner of 2016 presidential election."
    ]
  },{
    id : "70",
    events : [
      "1131 – Canute Lavard was murdered at Haraldsted, Denmark by his cousin, Magnus I of Sweden.",
      "1325 – Alfonso IV becomes King of Portugal.",
      "1558 – French troops, led by Francis, Duke of Guise, take Calais, the last continental possession of England.",
      "1566 – Pope Pius V is elected.",
      "1608 – Fire destroys Jamestown, Virginia.",
      "1610 – Galileo Galilei makes his first observation of the four Galilean moons: Ganymede, Callisto, Io and Europa, although he is not able to distinguish the last two until the following day.",
      "1738 – A peace treaty is signed between Peshwa Bajirao and Jai Singh II following Maratha victory in the Battle of Bhopal.",
      "1782 – The first American commercial bank, the Bank of North America, opens.",
      "1785 – Frenchman Jean-Pierre Blanchard and American John Jeffries travel from Dover, England, to Calais, France, in a gas balloon.",
      "1835 – HMS Beagle drops anchor off the Chonos Archipelago.",
      "1894 – William Kennedy Dickson receives a patent for motion picture film.",
      "1904 – The distress signal CQD is established only to be replaced two years later by SOS.",
      "1919 – Montenegrin guerrilla fighters rebel against the planned annexation of Montenegro by Serbia, but fail.",
      "1920 – The New York State Assembly refuses to seat five duly elected Socialist assemblymen.",
      "1922 – Dáil Éireann ratifies the Anglo-Irish Treaty by a 64–57 vote.",
      "1927 – The first transatlantic telephone service is established from New York City to London.",
      "1928 – A disastrous flood of the River Thames kills 14 people and causes extensive damage to much of riverside London.",
      "1931 – Guy Menzies flies the first solo non-stop trans-Tasman flight (from Australia to New Zealand) in 11 hours and 45 minutes, crash-landing on New Zealand's west coast.",
      "1935 – Benito Mussolini and French Foreign minister Pierre Laval sign the Franco-Italian Agreement.",
      "1939 – Marguerite Perey discovers Francium, the last element first discovered in nature, rather than by synthesis.",
      "1940 – Winter War: The Finnish 9th Division stop and completely destroy the numerically superior Soviet forces on the Raate-Suomussalmi road.",
      "1942 – World War II: The siege of the Bataan Peninsula begins.",
      "1945 – World War II: British General Bernard Montgomery holds a press conference in which he claims credit for victory in the Battle of the Bulge.",
      "1948 – Kentucky Air National Guard pilot Thomas Mantell crashes while in pursuit of a supposed UFO.",
      "1954 – Georgetown-IBM experiment: The first public demonstration of a machine translation system, is held in New York at the head office of IBM.",
      "1955 – Contralto Marian Anderson becomes the first person of color to perform at the Metropolitan Opera in Giuseppe Verdi's Un ballo in maschera.",
      "1959 – The United States recognizes the new Cuban government of Fidel Castro.",
      "1968 – Surveyor Program: Surveyor 7, the last spacecraft in the Surveyor series, lifts off from launch complex 36A, Cape Canaveral.",
      "1973 – Mark Essex fatally shoots ten people and wounds 13 others at Howard Johnson's Hotel in New Orleans, Louisiana, before being shot to death by police officers.",
      "1979 – Third Indochina War: Cambodian–Vietnamese War: Phnom Penh falls to the advancing Vietnamese troops, driving out Pol Pot and the Khmer Rouge.",
      "1980 – U.S. President Jimmy Carter authorizes legislation giving $1.5 billion in loans to bail out the Chrysler Corporation.",
      "1984 – Brunei becomes the sixth member of the Association of Southeast Asian Nations (ASEAN).",
      "1985 – Japan Aerospace Exploration Agency launches Sakigake, Japan's first interplanetary spacecraft and the first deep space probe to be launched by any country other than the United States or the Soviet Union.",
      "1991 – Roger Lafontant, former leader of the Tonton Macoute in Haiti under François Duvalier, attempts a coup d'état, which ends in his arrest.",
      "1993 – The Fourth Republic of Ghana is inaugurated with Jerry Rawlings as President.",
      "1993 – Bosnian War: The Bosnian Army executes a surprise attack at the village of Kravica in Srebrenica.",
      "1999 – The Senate trial in the impeachment of U.S. President Bill Clinton begins.",
      "2005 – Crevalcore train crash in Italy: 17 dead and dozens injured.",
      "2012 – A hot air balloon crashes near Carterton, New Zealand, killing all 11 people on board.",
      "2015 – Two gunmen commit mass murder at the offices of Charlie Hebdo in Paris, shooting twelve people execution style, and wounding eleven others.",
      "2015 – A car bomb explodes outside a police college in the Yemeni capital Sana'a with at least 38 people reported dead and more than 63 injured."
    ]
  },
 {
    id : "80",
    events : [
      "307 – Jin Huidi, Chinese emperor of the Jin Dynasty, is poisoned and succeeded by Jin Huaidi.",
      "871 – Alfred the Great leads a West Saxon army to repel an invasion by Danelaw Vikings.",
      "1297 – François Grimaldi, disguised as a monk, leads his men to capture the fortress protecting the Rock of Monaco, establishing his family as the rulers of Monaco.",
      "1499 – Louis XII of France marries Anne of Brittany in accordance with a law set by his predecessor, Charles VIII.",
      "1547 – The first Lithuanian-language book, Simple Words of Catechism, is published in Königsberg.",
      "1735 – Premiere performance of George Frideric Handel's Ariodante at the Royal Opera House, Covent Garden.",
      "1790 – George Washington delivers the first State of the Union address in New York City.",
      "1806 – Cape Colony becomes a British colony.",
      "1811 – An unsuccessful slave revolt is led by Charles Deslondes in St. Charles and St. James, Louisiana.",
      "1815 – War of 1812: Battle of New Orleans: Andrew Jackson leads American forces in victory over the British.",
      "1816 – Sophie Germain wins the Paris Academy of Sciences' Grand Prize for her mathematical work on Elasticity (physics).",
      "1835 – The United States national debt is zero for the only time.",
      "1863 – American Civil War: Second Battle of Springfield.",
      "1867 – African American men are granted the right to vote in Washington, D.C.",
      "1877 – Crazy Horse and his warriors fight their last battle against the United States Cavalry at Wolf Mountain, Montana Territory.",
      "1889 – Herman Hollerith is issued US patent #395,791 for the 'Art of Applying Statistics' — his punched card calculator.",
      "1912 – The African National Congress is founded.",
      "1918 – U.S. President Woodrow Wilson announces his Fourteen Points for the aftermath of World War I.",
      "1920 – The steel strike of 1919 ends in a complete failure for the Amalgamated Association of Iron, Steel and Tin Workers labor union.",
      "1925 – The All-Woman Supreme Court met for the first time in Texas, the first all-female supreme court in the history of the United States.",
      "1926 – Crown Prince Nguyễn Phúc Vĩnh Thuỵ ascends to the throne, the last monarch of Vietnam.",
      "1926 – Abdul-Aziz ibn Saud was crowned King of Hejaz.",
      "1936 – Kashf-e hijab decree is enforced by Reza Shah ordering the police to physically remove the Hijab from any woman in public.",
      "1940 – World War II: Britain introduces food rationing.",
      "1945 – World War II: Philippine Commonwealth troops under the Philippine Commonwealth Army units enter the province of Ilocos Sur in Northern Luzon and attack Japanese Imperial forces.",
      "1956 – Operation Auca: Five U.S. missionaries are killed by the Huaorani of Ecuador shortly after making contact with them.",
      "1961 – In France a referendum supports Charles de Gaulle's policies in Algeria.",
      "1963 – Leonardo da Vinci's Mona Lisa is exhibited in the United States for the first time, at the National Gallery of Art in Washington, D.C.",
      "1964 – President Lyndon B. Johnson declares a War on Poverty in the United States.",
      "1972 – Bowing to international pressure, President of Pakistan Zulfikar Ali Bhutto releases Bengali leader Sheikh Mujibur Rahman from prison, who had been arrested after declaring the independence of Bangladesh.",
      "1973 – Soviet space mission Luna 21 is launched.",
      "1973 – Watergate scandal: The trial of seven men accused of illegal entry into Democratic Party headquarters at Watergate begins.",
      "1975 – Ella T. Grasso becomes Governor of Connecticut, the first woman to serve as a Governor in the United States other than by succeeding her husband.",
      "1977 – Three bombs explode in Moscow, Russia, Soviet Union, within 37 minutes, killing seven. The bombings are attributed to an Armenian separatist group.",
      "1981 – A local farmer reports a UFO sighting in Trans-en-Provence, France, claimed to be perhaps the most completely and carefully documented sighting of all time.",
      "1982 – Breakup of the Bell System: AT&T agrees to divest itself of twenty-two subdivisions.",
      "1989 – Kegworth air disaster: British Midland Flight 92, a Boeing 737-400, crashes into the M1 motorway, killing 47 of the 126 people on board.",
      "1994 – Russian cosmonaut Valeri Polyakov on Soyuz TM-18 leaves for Mir. He would stay on the space station until March 22, 1995, for a record 437 days in space.",
      "1996 – An Antonov An-32 cargo aircraft crashes into a crowded market in Kinshasa, Zaire, killing up to 223 on the ground; two of six crew members are also killed.",
      "2002 – President George W. Bush signs into law the No Child Left Behind Act.",
      "2003 – Turkish Airlines Flight 634 crashes near Diyarbakır Airport, Turkey, killing the entire crew and 70 of the 75 passengers.",
      "2003 – Air Midwest Flight 5481 crashes at Charlotte-Douglas Airport, Charlotte, North Carolina, killing all 21 people on board.",
      "2004 – The RMS Queen Mary 2, the largest ocean liner ever built, is christened by her namesake's granddaughter, Queen Elizabeth II.",
      "2005 – The nuclear sub USS San Francisco collides at full speed with an undersea mountain south of Guam. One man is killed, but the sub surfaces and is repaired.",
      "2009 – A 6.1-magnitude earthquake in northern Costa Rica kills 15 people and injures 32.",
      "2010 – Gunmen from an offshoot the Front for the Liberation of the Enclave of Cabinda attack a bus carrying the Togo national football team on its way to the 2010 Africa Cup of Nations, killing three.",
      "2011 – The attempted assassination of Arizona Representative Gabrielle Giffords and subsequent shooting in Casas Adobes, Arizona, in which five people were shot dead.",
      "2016 - Joaquín Guzmán, widely regarded as the world's most powerful drug trafficker, is recaptured following his escape from a maximum security prison in Mexico."
    ]
 },{
    id : "90",
    events : [
      "475 – Byzantine Emperor Zeno is forced to flee his capital at Constantinople, and his general, Basiliscus gains control of the empire.",
      "681 – Twelfth Council of Toledo: King Erwig of the Visigoths initiates a council in which he implements diverse measures against the Jews in Spain.",
      "1127 – Jin–Song Wars: Invading Jurchen soldiers from the Jin dynasty besiege and sack Bianjing (Kaifeng), the capital of the Song dynasty of China, and abduct Emperor Qinzong of Song and others, ending the Northern Song dynasty.",
      "1150 – Wanyan Liang and other court officials murder Emperor Xizong of Jin. Wanyan Liang succeeds him as emperor.",
      "1349 – The Jewish population of Basel, believed by the residents to be the cause of the ongoing Black Death, is rounded up and incinerated.",
      "1431 – Judges' investigations for the trial of Joan of Arc begin in Rouen.",
      "1760 – Ahmad Shah Durrani defeats the Marathas in the Battle of Barari Ghat.",
      "1788 – Connecticut becomes the fifth state to ratify the Constitution.",
      "1792 – Treaty of Jassy between Russian and Ottoman Empire is signed.",
      "1793 – Jean-Pierre Blanchard becomes the first person to fly in a balloon in the United States.",
      "1799 – British Prime Minister William Pitt the Younger introduces an income tax of two shillings to the pound to raise funds for Great Britain's war effort in the Napoleonic Wars.",
      "1806 – Admiral Horatio Lord Nelson receives a state funeral and is interred in St Paul's Cathedral.",
      "1816 – Sir Humphry Davy tests his safety lamp for miners at Hebburn Colliery.",
      "1822 – The Portuguese prince Pedro I of Brazil decides to stay in Brazil against the orders of the Portuguese King João VI, beginning the Brazilian independence process.",
      "1839 – The French Academy of Sciences announces the Daguerreotype photography process.",
      "1857 – The 7.9 Mw  Fort Tejon earthquake shakes Central and Southern California with a maximum Mercalli intensity of IX (Violent).",
      "1858 – Anson Jones, the last President of the Republic of Texas, commits suicide.",
      "1861 – American Civil War: Star of the West incident occurs near Charleston, South Carolina.",
      "1861 – Mississippi becomes the second state to secede from the Union before the outbreak of the American Civil War.",
      "1878 – Umberto I becomes King of Italy.",
      "1894 – New England Telephone and Telegraph installs the first battery-operated telephone switchboard in Lexington, Massachusetts.",
      "1903 – Hallam Tennyson, 2nd Baron Tennyson, son of the poet Alfred Tennyson, becomes the second Governor-General of Australia.",
      "1909 – Ernest Shackleton, leading the Nimrod Expedition to the South Pole, plants the British flag 97 nautical miles (180 km; 112 mi) from the South Pole, the farthest anyone had ever reached at that time.",
      "1914 – Phi Beta Sigma Fraternity Inc., the first historically black intercollegiate Greek-letter fraternity to be officially recognized at Howard University, is founded.",
      "1916 – World War I: The Battle of Gallipoli concludes with an Ottoman Empire victory when the last Allied forces are evacuated from the peninsula.",
      "1917 – World War I: The Battle of Rafa is fought near the Egyptian border with Palestine.",
      "1918 – Battle of Bear Valley: The last battle of the American Indian Wars.",
      "1921 – Greco-Turkish War: The First Battle of İnönü, the first battle of the war, begins near Eskişehir in Anatolia.",
      "1923 – Juan de la Cierva makes the first autogyro flight.",
      "1923 – Lithuanian residents of the Memel Territory rebel against the League of Nations' decision to leave the area as a mandated region under French control.",
      "1927 – A fire at the Laurier Palace movie theatre in Montreal, Quebec, Canada, kills 78 children.",
      "1941 – World War II: First flight of the Avro Lancaster.",
      "1945 – World War II: The Sixth United States Army begins the invasion of Lingayen Gulf.",
      "1957 – British Prime Minister Sir Anthony Eden resigns from office following his failure to retake the Suez Canal from Egyptian sovereignty.",
      "1960 – President of Egypt Gamal Abdel Nasser opens construction on the Aswan Dam by detonating ten tons of dynamite to demolish twenty tons of granite on the east bank of the Nile.",
      "1961 – British authorities announce they have uncovered the Soviet Portland Spy Ring in London.",
      "1964 – Martyrs' Day: Several Panamanian youths try to raise the Panamanian flag in the U.S.-controlled Panama Canal Zone, leading to fighting between U.S. military and Panamanian civilians.",
      "1965 – The Mirzapur Cadet College formally opens for academic activities in East Pakistan (now Bangladesh).",
      "1991 – Representatives from the United States and Iraq meet at the Geneva Peace Conference to try to find a peaceful resolution to the Iraqi invasion of Kuwait.",
      "1992 – The Assembly of the Serb People in Bosnia and Herzegovina proclaims the creation of Republika Srpska, a new state within Yugoslavia.",
      "1992 – The first discoveries of extrasolar planets are announced by astronomers Aleksander Wolszczan and Dale Frail. They discovered two planets orbiting the pulsar PSR 1257+12.[1]",
      "1996 – First Chechen War: Chechen separatists launch a raid against the helicopter airfield and later a civilian hospital in the city of Kizlyar in the neighboring Dagestan, which turns into a massive hostage crisis involving thousands of civilians.",
      "2004 – An inflatable boat carrying illegal Albanian emigrants stalls near the Karaburun Peninsula en route to Brindisi, Italy; exposure to the elements kills 28. This is the second deadliest marine disaster in Albanian history.",
      "2005 – Mahmoud Abbas wins the election to succeed Yasser Arafat as President of the Palestinian National Authority, replacing interim president Rawhi Fattouh.",
      "2005 – The Sudan People's Liberation Movement and the Government of Sudan sign the Comprehensive Peace Agreement to end the Second Sudanese Civil War.",
      "2007 – Apple CEO Steve Jobs introduces the original iPhone at a Macworld keynote in San Francisco.",
      "2011 – Iran Air Flight 277 crashes near Orumiyeh in the northwest of the country, killing 77 people.",
      "2014 – An explosion at a Mitsubishi Materials chemical plant in Yokkaichi, Japan, kills at least five people and injures 17 others.",
      "2015 – The perpetrators of the Charlie Hebdo shooting in Paris two days earlier are both killed after a hostage situation; a second hostage situation, related to the Charlie Hebdo shooting, occurs at a Jewish market in Vincennes.",
      "2019 – The new host for the 2019 Africa Cup of Nations will be chosen in Dakar, Senegal."
    ]
  }];
  module.exports=ob ;